---
- name: Ensure nginx is installed
  apt: pkg=nginx state=present default_release={{ nginx_default_distribution|default(omit) }}
  tags:
    - system
    - install

- name: Ensure openssl is installed
  apt: pkg=openssl state=present
  when: nginx_ssl
  tags:
    - system
    - install

- name: Ensure all folders exists
  file: path="/etc/nginx/{{ item }}" state=directory
  with_items:
    - sites-available
    - sites-enabled
    - conf.d

- name: Ensure configuration is set
  template: src={{ item.src }} dest=/etc/nginx/{{ item.path }}
  with_filetree:
    - ../templates
  when: item.state == 'file'
  loop_control:
      label: '{{ item.path }}'
  notify: restart nginx
  tags:
    - config

- name: Ensure cache dir exists
  file: path={{ nginx_cache_dir }} state=directory owner={{ nginx_user }} mode=0700

- name: Ensure dhparam is set created
  command: openssl dhparam -out {{ nginx_dhparam_path }} {{ nginx_dhparam_size }} creates={{ nginx_dhparam_path }}
  when: nginx_ssl

- name: Ensure service is started at boot
  service: name=nginx enabled=yes

- name: Install Let's Encrypt renewal hook
  copy: src=letsencrypt-hook dest={{ letsencrypt__config_root }}/renewal-hooks/deploy/nginx mode=0744
  when: letsencrypt__config_root is defined
  notify: restart nginx
