---
csvapi__version: 1.0.0
csvapi__user: csvapi
csvapi__server_name: csvapi.company.com
csvapi__home: /srv/csvapi
csvapi__home_dbs: "{{csvapi__home}}/dbs"
csvapi__config: "{{csvapi__home}}/config.py"
csvapi__nginx_logs: "/var/log/nginx/{{csvapi__server_name}}"
# Define this to a certificate object to enable SSL
csvapi__ssl_certificate: false
csvapi__workers: 3
csvapi__sentry_dsn:
csvapi__csv_sniff_limit: 4096
csvapi__max_file_size: 104857600
csvapi__debug: false
csvapi__allowed_referrers: []

hypercorn__user: "{{csvapi__user}}"
hypercorn__app: csvapi.webservice:app
hypercorn__workers: 3
hypercorn__bind_port: 8080
hypercorn__bind_host: 127.0.0.1
hypercorn__log_dir: /var/log/hypercorn
hypercorn__access_log: "{{hypercorn__log_dir}}/{{csvapi__server_name}}.access.log"
hypercorn__error_log: "{{hypercorn__log_dir}}/{{csvapi__server_name}}.error.log"
hypercorn__binary: "{{csvapi__home}}/bin/hypercorn"
hypercorn__limit_no_file: 1024
